name: adversarial-robustness-toolbox
version: '0.1' 
summary: Adversarial Robustness Toolbox
description: |
  This is a library dedicated to adversarial machine learning. Its purpose is
  to allow rapid crafting and analysis of attacks and defense methods for
  machine learning models. The Adversarial Robustness Toolbox provides an
  implementation for many state-of-the-art methods for attacking and defending
  classifiers.

grade: stable
confinement: strict

parts:
  adversarial-robustness-toolbox:
    source: https://github.com/IBM/adversarial-robustness-toolbox.git
    plugin: python
    python-version: python3
    stage-packages: [python3-numpy, python3-h5py,python3-matplotlib,python3-scipy,python3-sphinx,python3-sphinx-rtd-theme]
    requirements: requirements.txt
    process-dependency-links: true

apps:
  adversarial-robustness-toolbox:
    command: bash run_tests.sh
